name: Build Psych Extended Online

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup & Build
        run: |
          .\setup\windows.bat
          lime build windows -D officialBuild -final
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-x86_64
          path: export/release/windows/bin/
